SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
    JOIN ITEM_TREE T 
    ON I.ITEM_ID = T.ITEM_ID
    JOIN ITEM_INFO A
    ON T.PARENT_ITEM_ID = A.ITEM_ID
WHERE A.RARITY = 'RARE'
ORDER BY ITEM_ID DESC